### ISSUE TITLE
Ugly element borders

### ISSUE THREAD

**Issue by wexcore** [db0/div0-theme#2]
The following borders look (subjectively) ugly. Consider removing them.

In the "post-listings" class on the community page:
![post-listings](https://github.com/db0/div0-theme/assets/19491308/460993c6-e5a1-47af-b0c3-e8d58c8196b1)

And in the "postContent" class on the post:
![postContent](https://github.com/db0/div0-theme/assets/19491308/6186ff74-8980-4088-b60f-daeb6e5fa9ca)

**Comment by RandomLegend** [comment]
i'll make a version of this without any roundness. 

As of i right now, the get the correct padding between elements i'd have to build the .css files from source and change those factors in the sourcecode. I am looking into it.

**Comment by RandomLegend** [comment]
btw. the distorted borders in the first screenshot appears to be a local issue on your side.

i tested it now with 3 different browsers on two different machines with and without any cached data. For me it looks perfectly fine everytime. No blockyness.

**Comment by wexcore** [comment]
Sorry for the confusion. I'm okay with them being round, i just don't like how this borders look inside another border. In my opinion it looks somewhat cleaner without them.

![without-borders](https://github.com/db0/div0-theme/assets/19491308/5b29ca01-aaa7-404c-9b8b-4212c5d26712)

Same results for the blocky border on my phone:

![chrome-android](https://github.com/db0/div0-theme/assets/19491308/ece7c2a4-54da-4206-a1ad-00965d038cba)

Seems to be the overlap with the background color from "mt-2" class element.

**Comment by RandomLegend** [comment]
Fixed via https://github.com/db0/div0-theme/pull/4
